### ISSUE TITLE
Thermostat input via the serial port?

### ISSUE THREAD

**Issue by themmes** [rjblake/remeha#10]
Hi Richard,

First of all, amazing to see that there is actually open source projects addressing the Remeha boiler. Thank you for that!

Sorry for my ignorance, but does the boiler also accepts input via this port? Or would you advise to route inputs through the on/off or modulation ports on the boiler.

Looking forward to your reply!

**Comment by rjblake** [comment]
Tom (@themmes) - I would not suggest using this port for inputs (i.e. thermostat/demand) as it currently does not have any recovery for failed/incomplete commands and could make a mess of things. I did add some code (privately) to make a few parameter changes; but it did cause an issue that required a boiler reconfiguration/restart; so definitely not ready for sharing with a wider audience.
In addition, the port is not meant for this purpose, but rather diagnostics/configuration with the Remeha tools

**Comment by themmes** [comment]
@rjblake Thank you very much for your quick reply!

Thats clear, thank you. I will start looking into Open-therm boards to interface with the modulation input channel. After that I should probably start monitoring via the PDA interface and will revisit your project.

**Comment by rjblake** [comment]
@themmes - I had an OpenTherm gateway connected previously with the intent to use to control boiler. In the end, I decided to leave the modulation requests to a Tado thermostat (simpler and can also control this with my Domoticz setup). It was not worth the extra effort to create all this functionality in a separate device. Could have done the same with the Eneco Toon, but dumped this as had numerous issues with it connecting to my WiFi. I have various scripts in Domoticz that open/close valves in different parts of the house to balance the heating better.
