### ISSUE TITLE
How to get Informations into Domoticz

### ISSUE THREAD

**Issue by cvastag** [rjblake/remeha#9]
Hello, thanks for sharing your files. 
I get connection to boiler, but I don't know how to get these informations into Domoticz.
I added IP Adress of the domoticz server into the script. But i don't see a sensor. 
Can you help me?

**Comment by rjblake** [comment]
Check the file remeha.ini - this has sections for entering your Domoticz server details as well as all the various devices you need to create in Domoticz. These need to be done manually as are not created by the scripts. Change out the ID with the ID that matches your devices
